# Pulled from https://hub.docker.com/r/linuxserver/openssh-server

version: '3.7'
services:
  proxy:
    image: linuxserver/openssh-server
    container_name: proxy_ssh
    hostname: proxy #optional
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: 'USA/Oregon'
      # PUBLIC_KEY: 'pub-key-goes-here' #optional
      SUDO_ACCESS: 'false' #optional
      # PASSWORD_ACCESS: 'false' #optional
      # USER_PASSWORD: 'password' #optional
      # USER_PASSWORD_FILE: '/path/to/file' #optional
      USER_NAME: 'proxy' #optional
    volumes:
      - ./config/:/config
    ports:
      - '2222:2222'
      - '80:8080'
      - '443:4443'
    restart: unless-stopped
