# Pulled from https://hub.docker.com/r/linuxserver/openssh-server

version: '3.7'
services:
  proxy_http:
    image: linuxserver/openssh-server
    container_name: proxy_http
    hostname: proxy #optional
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: 'USA/Oregon'
      PUBLIC_KEY: 'yourpublickey' #optional
      PUBLIC_KEY_FILE: '/path/to/file' #optional
      SUDO_ACCESS: 'false' #optional
      # PASSWORD_ACCESS: 'false' #optional
      # USER_PASSWORD: 'password' #optional
      # USER_PASSWORD_FILE: '/path/to/file' #optional
      USER_NAME: 'proxy' #optional
    # volumes:
    #   - /path/to/appdata/config:/config
    ports:
      - '80:8080'
      - '443:4443'
    restart: unless-stopped
  proxy_ssh:
    image: linuxserver/openssh-server
    container_name: proxy_ssh
    hostname: proxy #optional
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: 'USA/Oregon'
      PUBLIC_KEY: 'ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDYWsUWt1ywdOlAD5sYQvlW/SyEsvv6BIm+vjoLaFruHtPVytmRvG3mz0ItGrUYZzp7iiDvQwR3YQxgFhwmW6wY=' #optional
      SUDO_ACCESS: 'false' #optional
      # PASSWORD_ACCESS: 'false' #optional
      # USER_PASSWORD: 'password' #optional
      # USER_PASSWORD_FILE: '/path/to/file' #optional
      USER_NAME: 'proxy' #optional
    # volumes:
    #   - /path/to/appdata/config:/config
    ports:
      - '2222:2222'
    restart: unless-stopped
