version: '3.4'

services:
  sshtunneller:
    image: jossec101/sshtunneller
    container_name: sshtunneller
    hostname: sshtunneller
    ports:
      - '3000:80'
    environment:
      ssh_host: proxy.rothanaheavyengineering.org
      ssh_port: 22
      ssh_username: root
      #- ssh_password=This_Is_a_SSH_P4SSW0RD
      ssh_private_key_password: ${PRIVATE_KEY_PASS}
      remote_bind_addresses: '[("54.245.187.111", 80)]'
      local_bind_addresses: '[("127.0.0.1", 80)]'
    volumes:
      - ~/.ssh/id_ecdsa:/private.key
    restart: unless-stopped
